steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      [
        "build_and_deploy.sh",
        "$BRANCH_NAME"
      ]
substitutions:
  _USE_SITE_GATING: 'false'
  _SITE_GATING_MATCH: 'null'
images:
  - "gcr.io/$PROJECT_ID/react-app"
