steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: bash
    args:
      [
        "build_and_deploy.sh",
        "$BRANCH_NAME",
        "$_USE_SITE_GATING",
        "$_SITE_GATING_MATCH"
      ]
    secretEnv: ['SENTRY_AUTH_TOKEN']
availableSecrets:
  secretManager:
  - versionName: projects/220082085305/secrets/SENTRY_AUTH_TOKEN/versions/latest
    env: 'SENTRY_AUTH_TOKEN'
substitutions:
  _USE_SITE_GATING: 'false'
  _SITE_GATING_MATCH: 'null'
