FROM node:16 as build-stage
WORKDIR app
COPY ./ /app/
RUN git submodule init 
# RUN cd ./src/maphooks && yarn && cd ../..
RUN yarn
EXPOSE 3000

ARG REACT_APP_USE_SITE_GATING=0
ENV REACT_APP_USE_SITE_GATING $REACT_APP_USE_SITE_GATING

ARG REACT_APP_SITE_GATING_MATCH=default_value
ENV REACT_APP_SITE_GATING_MATCH $REACT_APP_SITE_GATING_MATCH

ENTRYPOINT [ "npm", "start" ]