FROM cypress/base:16

WORKDIR /app
COPY ./ /app/
RUN yarn
EXPOSE 3000

ARG REACT_APP_USE_SITE_GATING=0
ENV REACT_APP_USE_SITE_GATING $REACT_APP_USE_SITE_GATING

ARG REACT_APP_SITE_GATING_MATCH=default_value
ENV REACT_APP_SITE_GATING_MATCH $REACT_APP_SITE_GATING_MATCH

RUN npm install --save-dev start-server-and-test
RUN yarn cypress:ci

# ENTRYPOINT [ "npm", "start" ]