// AEB REP PTS
import {
  Blue_5Step,
  Blue_5Step_0_1,
  Blue_5Step_per_ha,
  Red_10Step_0_1,
  Red_10Step_negative1_positive1,
  SelectedTessela,
  FloodMaps_Bathy,
  Empty,
  Mangroves,
  Green,
} from "./colormaps/colormaps";

const annual_benefits = [
  {
    id: "tessela_bounds",
    source: "tesselas",
    source_layer: "Tesselas",
    legend: SelectedTessela,
    layer_title: "Tessela",
    layer_type: "SIMPLE_OUTLINE",
    selection_dependent_on: "RP",
  },
  {
    id: "countries",
    source: "countries",
    source_layer: "Countries",
    colorValue: ["to-number", ["get", "Ab_S_BAE"]],
    legend: Blue_5Step,
    layer_title: "Tessela",
    layer_type: "FILL_WITH_OUTLINE",
    minzoom: 0,
    maxzoom: 4,
    opacity: 0.9,
    display_legend: false,
    is_selectable: true,
  },
  {
    id: "tessela_rps",
    source: "tesselas",
    source_layer: "RP",
    colorValue: ["to-number", ["get", "Ab_S_BAE"]],
    legend: Blue_5Step,
    layer_title: "Annual Expected Benefit",
    layer_type: "DISCRETE_POINT",
    legend_prefix: "$",
    format: "$",
    is_selectable: true,
  },
];

const reduct_ratio = [
  {
    id: "tessela_bounds",
    source: "tesselas",
    source_layer: "Tesselas",
    legend: SelectedTessela,
    layer_title: "Tessela",
    layer_type: "SIMPLE_OUTLINE",
    selection_dependent_on: "Hex_p035",
  },
  {
    id: "countries",
    source: "countries",
    source_layer: "Countries",
    colorValue: [
      "case",
      ["==", ["to-number", ["get", "Ab_S_WoAE"]], 0],
      0,
      [
        "-",
        1,
        [
          "to-number",
          [
            "/",
            ["to-number", ["get", "Ab_S_WAE"]],
            ["to-number", ["get", "Ab_S_WoAE"]],
          ],
        ],
      ],
    ],
    legend: Blue_5Step_0_1,
    layer_title: "Tessela",
    layer_type: "FILL_WITH_OUTLINE",
    display_legend: false,
    minzoom: 0,
    maxzoom: 4,
    opacity: 0.9,
    is_selectable: true,
  },
  {
    id: "hex",
    source: "tesselas",
    source_layer: "Hex_p035",
    legend: Blue_5Step_0_1,
    colorValue: [
      "case",
      ["==", ["to-number", ["get", "Ab_S_WoAE"]], 0],
      0,
      [
        "-",
        1,
        [
          "to-number",
          [
            "/",
            ["to-number", ["get", "Ab_S_WAE"]],
            ["to-number", ["get", "Ab_S_WoAE"]],
          ],
        ],
      ],
    ],
    heightValue: ["get", "Ab_S_WoAE"],
    baseValue: ["get", "Ab_S_WAE"],
    scale: 0.5,
    legend: Blue_5Step_0_1,
    layer_title: "Risk Reduction",
    layer_type: "HEX_3D",
    hex_type: "REDUCTION",
    legend_suffix: "%",
    format: "%",
    display_legend: true,
    is_selectable: true,
  },
  {
    id: "hex2",
    source: "tesselas",
    source_layer: "Hex_p035",
    legend: Blue_5Step_0_1,
    colorValue: "white",
    heightValue: ["get", "Ab_S_WAE"],
    baseValue: 0,
    scale: 0.5,
    layer_title: "Tessela",
    layer_type: "HEX_3D",
    hex_type: "BASE",
    legend_suffix: "%",
    format: "%",
    display_legend: false,
    is_selectable: true,
  },
];

const per_ha = [
  {
    id: "tessela_bounds",
    source: "tesselas",
    source_layer: "Tesselas",
    legend: SelectedTessela,
    layer_title: "Tessela",
    layer_type: "SIMPLE_OUTLINE",
    selection_dependent_on: "RP",
  },
  {
    id: "countries",
    source: "countries",
    source_layer: "Countries",
    colorValue: [
      "case",
      ["==", ["to-number", ["get", "Man2010"]], 0],
      0,
      [
        "/",
        ["to-number", ["get", "Ab_S_BAE"]],
        ["to-number", ["get", "Man2010"]],
      ],
    ],
    legend: Blue_5Step_per_ha,
    layer_title: "Tessela",
    layer_type: "FILL_WITH_OUTLINE",
    minzoom: 0,
    maxzoom: 4,
    display_legend: false,
    opacity: 0.9,
    is_selectable: true,
  },
  {
    id: "tessela_rps",
    source: "tesselas",
    source_layer: "RP",
    colorValue: [
      "case",
      ["==", ["to-number", ["get", "Man2010"]], 0],
      0,
      [
        "/",
        ["to-number", ["get", "Ab_S_BAE"]],
        ["to-number", ["get", "Man2010"]],
      ],
    ],
    legend: Blue_5Step_per_ha,
    layer_title: "Benefit per Hectare",
    layer_type: "DISCRETE_POINT",
    legend_prefix: "$",
    format: "$",
    is_selectable: true,
  },
];

const flooding = [
  // ******************
  // WITH
  // ******************
  {
    id: "flooding_without0",
    source: "flooding_without",
    source_layer: "T0",
    legend: FloodMaps_Bathy,
    // colorValue: ['to-number', ['get', 'grid_code']],
    colorValue: "rgba(255, 255, 255, 0.8)",
    layer_title: "Without Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    is_subgroup: true,
    display_legend: true,
    minzoom: 6,
  },
  {
    id: "flooding_without1",
    source: "flooding_without",
    source_layer: "T1",
    legend: FloodMaps_Bathy,
    // colorValue: ['to-number', ['get', 'grid_code']],
    colorValue: "#bae4bc",
    layer_title: "Without Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    is_subgroup: true,
    minzoom: 6,
  },
  {
    id: "flooding_without2",
    source: "flooding_without",
    source_layer: "T2",
    legend: FloodMaps_Bathy,
    // colorValue: ['to-number', ['get', 'grid_code']],
    colorValue: "#7bccc4",
    layer_title: "Without Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    is_subgroup: true,
    minzoom: 6,
  },
  {
    id: "flooding_without3",
    source: "flooding_without",
    source_layer: "T3",
    legend: FloodMaps_Bathy,
    // colorValue: ['to-number', ['get', 'grid_code']],
    colorValue: "#43a2ca",
    layer_title: "Without Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    is_subgroup: true,
    minzoom: 6,
  },
  {
    id: "flooding_without4",
    source: "flooding_without",
    source_layer: "T4",
    legend: FloodMaps_Bathy,
    // colorValue: ['to-number', ['get', 'grid_code']],
    colorValue: "#0868ac",
    layer_title: "Without Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    is_subgroup: true,
    minzoom: 6,
  },
  {
    id: "flooding_without5",
    source: "flooding_without",
    source_layer: "T5",
    legend: FloodMaps_Bathy,
    // colorValue: ['to-number', ['get', 'grid_code']],
    colorValue: "#0868ac",
    layer_title: "Without Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    is_subgroup: true,
    minzoom: 5,
  },
  {
    id: "flooding_without6",
    source: "flooding_without",
    source_layer: "T6",
    legend: FloodMaps_Bathy,
    // colorValue: ['to-number', ['get', 'grid_code']],
    colorValue: "#0868ac",
    layer_title: "Without Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    is_subgroup: true,
    minzoom: 4,
  },
  // ******************
  // WITH
  // ******************
  {
    id: "flooding_with0",
    source: "flooding_with",
    source_layer: "T0",
    legend: FloodMaps_Bathy,
    // colorValue: ['to-number', ['get', 'grid_code']],
    colorValue: "rgba(255, 255, 255, 0.8)",
    layer_title: "With Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    is_subgroup: true,
    display_legend: true,
    minzoom: 6,
  },
  {
    id: "flooding_with1",
    source: "flooding_with",
    source_layer: "T1",
    legend: FloodMaps_Bathy,
    // colorValue: ['to-number', ['get', 'grid_code']],
    colorValue: "#bae4bc",
    layer_title: "Without Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    is_subgroup: true,
    minzoom: 6,
  },
  {
    id: "flooding_with2",
    source: "flooding_with",
    source_layer: "T2",
    legend: FloodMaps_Bathy,
    // colorValue: ['to-number', ['get', 'grid_code']],
    colorValue: "#7bccc4",
    layer_title: "Without Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    is_subgroup: true,
    minzoom: 6,
  },
  {
    id: "flooding_with3",
    source: "flooding_with",
    source_layer: "T3",
    legend: FloodMaps_Bathy,
    // colorValue: ['to-number', ['get', 'grid_code']],
    colorValue: "#43a2ca",
    layer_title: "Without Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    is_subgroup: true,
    minzoom: 6,
  },
  {
    id: "flooding_with4",
    source: "flooding_with",
    source_layer: "T4",
    legend: FloodMaps_Bathy,
    // colorValue: ['to-number', ['get', 'grid_code']],
    colorValue: "#0868ac",
    layer_title: "Without Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    is_subgroup: true,
    minzoom: 6,
  },
  {
    id: "flooding_with5",
    source: "flooding_with",
    source_layer: "T5",
    legend: FloodMaps_Bathy,
    colorValue: "#0868ac",
    layer_title: "Without Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    is_subgroup: true,
    minzoom: 5,
  },
  {
    id: "flooding_with6",
    source: "flooding_with",
    source_layer: "T6",
    legend: FloodMaps_Bathy,
    colorValue: "#0868ac",
    layer_title: "Without Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    is_subgroup: true,
    minzoom: 4,
  },
  {
    id: "tessela_rps",
    source: "tesselas",
    source_layer: "RP",
    colorValue: ["to-number", ["get", "Ab_S_BAE"]],
    legend: Empty,
    layer_title: "Annual Expected Benefit",
    layer_type: "DISCRETE_POINT",
    legend_prefix: "$",
    format: "$",
    display_legend: false,
  },
  {
    id: "tessela_bounds",
    source: "tesselas",
    source_layer: "Tesselas",
    legend: SelectedTessela,
    layer_title: "Tessela",
    layer_type: "SIMPLE_OUTLINE",
    selection_dependent_on: "RP",
  },
];

const flooding_test = [
  {
    id: "mangroves_2015",
    source: "mangroves_2015",
    source_layer: "cf23fc24843b11eeb772b580fc9aa31f",
    legend: Mangroves,
    layer_title: "Mangroves 2015",
    colorValue: ["to-number", ["get", "PXLVAL"]],
    legend: Green,
    layer_type: "FILL_WITH_OUTLINE",
    display_legend: false,
    subgroup: "flooding_2015",
    opacity: 1,
    minzoom: 4,
    maxzoom: 18,
  },
  {
    id: "mangroves_1996",
    source: "mangroves_1996",
    source_layer: "GMW_1996_v3_Areas",
    legend: Mangroves,
    layer_title: "Mangroves 1996",
    colorValue: ["to-number", ["get", "PXLVAL"]],
    legend: Green,
    layer_type: "FILL_WITH_OUTLINE",
    display_legend: false,
    subgroup: "flooding_1996",
    opacity: 1,
    minzoom: 4,
    maxzoom: 18,
  },
  {
    id: "flooding_1996",
    source: "flooding_1996_pt",
    source_layer: "with_1996_TC_Tr_100",
    legend: FloodMaps_Bathy,
    colorValue: ["to-number", ["get", "value"]],
    layer_title: "Without Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    subgroup: "flooding_1996",
    minzoom: 4,
  },
  {
    id: "flooding_2015",
    source: "flooding_2015_pt",
    source_layer: "with_2015_TC_Tr_100",
    legend: FloodMaps_Bathy,
    colorValue: ["to-number", ["get", "value"]],
    layer_title: "Without Mangroves, RP50",
    layer_type: "GEO_POINT",
    legend_suffix: "m",
    subgroup: "flooding_2015",
    minzoom: 4,
  },
];

const SHDI = [
  {
    id: "tessela_bounds",
    source: "CWON_tesela_bounds",
    source_layer: "CWON_combined_teselas",
    legend: SelectedTessela,
    layer_title: "Tessela",
    layer_type: "SIMPLE_OUTLINE",
    selection_dependent_on: "CWON_combined_teselas_reppts",
  },
  {
    id: "tessela_rps",
    source: "CWON_tesela_reppts",
    source_layer: "CWON_combined_teselas_reppts",
    colorValue: ["to-number", ["get", "SHDI_2015"]],
    legend: Red_10Step_0_1,
    layer_title: "Annual Expected Benefit",
    layer_type: "DISCRETE_POINT",
    legend_prefix: "",
    // format: "$",
    is_selectable: true,
  },
];

const MangroveLoss = [
  {
    id: "tessela_bounds",
    source: "CWON_tesela_bounds",
    source_layer: "CWON_combined_teselas",
    legend: SelectedTessela,
    layer_title: "Tessela",
    layer_type: "SIMPLE_OUTLINE",
    selection_dependent_on: "CWON_combined_teselas_reppts",
  },
  {
    id: "tessela_rps",
    source: "CWON_tesela_reppts",
    source_layer: "CWON_combined_teselas_reppts",
    colorValue: [
      "/",
      [
        "-",
        ["to-number", ["get", "Mang_Ha_2020"]],
        ["to-number", ["get", "Mang_Ha_1996"]],
      ],
      ["+", ["to-number", ["get", "Mang_Ha_1996"]], 1], //Divide by zero
    ],
    legend: Red_10Step_negative1_positive1,
    layer_title: "Annual Expected Benefit",
    layer_type: "DISCRETE_POINT",
    legend_prefix: "",
    format: "%",
    is_selectable: true,
  },
];

const layers = {
  "Benefit (AEB)": annual_benefits,
  "Benefit per Hectare": per_ha,
  "Risk Reduction Ratio": reduct_ratio,
  Flooding: flooding_test,
  SHDI: SHDI,
  MangLoss: MangroveLoss,
};

export default layers;
