name: Cypress end-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Sentry CLI
        uses: mathieu-bour/setup-sentry-cli@v1
        with:
          token: ${{ SECRETS.SENTRY_AUTH_TOKEN }} # from GitHub secrets
          organization: whitecap
          project: global-flood-explorer
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npx serve -s build 
          wait-on: http://localhost:3000
        env:
          DISABLE_ESLINT_PLUGIN: true
